import React, { useState, useRef, useEffect } from 'react';

const Chatbot = ({ courseId, chapterId }) => {
  const [messages, setMessages] = useState([
    {
      id: 1,
      type: 'bot',
      content: 'Hello! I\'m your AI study assistant. I can help answer questions about the textbook content. What would you like to know?',
      timestamp: new Date().toISOString()
    }
  ]);
  const [inputMessage, setInputMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const sendMessage = async () => {
    if (!inputMessage.trim() || isLoading) return;

    const userMessage = {
      id: Date.now(),
      type: 'user',
      content: inputMessage.trim(),
      timestamp: new Date().toISOString()
    };

    // Add user message to chat
    setMessages(prev => [...prev, userMessage]);
    setInputMessage('');
    setIsLoading(true);
    setIsTyping(true);

    try {
      // In a real implementation, this would call the backend API
      // For now, we'll simulate with a mock response
      await new Promise(resolve => setTimeout(resolve, 1000)); // Simulate API delay

      // Mock response based on the API contract
      const mockResponse = {
        question_id: `mock-${Date.now()}`,
        question: inputMessage.trim(),
        answer: `This is a simulated response to your question: "${inputMessage.trim()}". In a real implementation, this would be generated by the RAG system based on textbook content. The AI would search through the relevant chapters and provide an accurate, context-aware answer with sources.`,
        sources: [
          {
            chapter_id: chapterId || 'mock-chapter-id',
            chapter_title: 'Relevant Chapter',
            content_snippet: 'This is a sample content snippet from the textbook...',
            relevance_score: 0.85
          }
        ],
        confidence_score: 0.9,
        timestamp: new Date().toISOString()
      };

      const botMessage = {
        id: Date.now() + 1,
        type: 'bot',
        content: mockResponse.answer,
        sources: mockResponse.sources,
        timestamp: mockResponse.timestamp
      };

      setMessages(prev => [...prev, botMessage]);
    } catch (error) {
      const errorMessage = {
        id: Date.now() + 1,
        type: 'bot',
        content: 'Sorry, I encountered an error processing your question. Please try again.',
        timestamp: new Date().toISOString()
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
      setIsTyping(false);
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const quickQuestions = [
    "What is Physical AI?",
    "Explain humanoid robotics",
    "How do robots learn?",
    "What is kinematics?"
  ];

  const handleQuickQuestion = (question) => {
    setInputMessage(question);
    setTimeout(() => {
      inputRef.current?.focus();
    }, 100);
  };

  return (
    <div className="chatbot-container">
      <div className="chatbot-header">
        <h3>AI Study Assistant</h3>
        <p>Ask questions about the textbook content</p>
      </div>

      <div className="chatbot-messages">
        {messages.map((message) => (
          <div
            key={message.id}
            className={`message ${message.type}`}
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: message.type === 'user' ? 'flex-end' : 'flex-start',
              marginBottom: '1rem'
            }}
          >
            <div
              style={{
                maxWidth: '80%',
                padding: '0.75rem 1rem',
                borderRadius: '18px',
                backgroundColor: message.type === 'user' ? '#007bff' : '#f8f9fa',
                color: message.type === 'user' ? 'white' : 'black',
                wordWrap: 'break-word',
                boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
              }}
            >
              <div style={{ marginBottom: '0.25rem' }}>
                {message.content}
              </div>

              {message.sources && message.sources.length > 0 && (
                <div style={{ marginTop: '0.5rem', fontSize: '0.85rem', color: '#666' }}>
                  <strong>Sources:</strong>
                  {message.sources.map((source, idx) => (
                    <div key={idx} style={{ marginTop: '0.25rem', paddingLeft: '0.5rem' }}>
                      {source.chapter_title}
                    </div>
                  ))}
                </div>
              )}
            </div>
            <div style={{ fontSize: '0.75rem', color: '#999', marginTop: '0.25rem' }}>
              {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
            </div>
          </div>
        ))}

        {isTyping && (
          <div
            className="message bot"
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'flex-start',
              marginBottom: '1rem'
            }}
          >
            <div
              style={{
                maxWidth: '80%',
                padding: '0.75rem 1rem',
                borderRadius: '18px',
                backgroundColor: '#f8f9fa',
                color: 'black',
                wordWrap: 'break-word',
                boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
              }}
            >
              <div className="typing-indicator">
                <span></span>
                <span></span>
                <span></span>
              </div>
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {messages.length === 1 && (
        <div className="quick-questions">
          <p>Try asking:</p>
          <div className="quick-questions-grid">
            {quickQuestions.map((question, index) => (
              <button
                key={index}
                onClick={() => handleQuickQuestion(question)}
                className="quick-question-btn"
              >
                {question}
              </button>
            ))}
          </div>
        </div>
      )}

      <div className="chatbot-input">
        <textarea
          ref={inputRef}
          value={inputMessage}
          onChange={(e) => setInputMessage(e.target.value)}
          onKeyPress={handleKeyPress}
          placeholder="Ask a question about the textbook content..."
          disabled={isLoading}
          rows={2}
          style={{
            width: '100%',
            padding: '0.75rem',
            borderRadius: '20px',
            border: '1px solid #ddd',
            resize: 'none',
            fontSize: '1rem',
            marginRight: '0.5rem'
          }}
        />
        <button
          onClick={sendMessage}
          disabled={!inputMessage.trim() || isLoading}
          style={{
            padding: '0.75rem 1.5rem',
            backgroundColor: '#007bff',
            color: 'white',
            border: 'none',
            borderRadius: '20px',
            cursor: (!inputMessage.trim() || isLoading) ? 'not-allowed' : 'pointer',
            fontSize: '1rem'
          }}
        >
          {isLoading ? 'Sending...' : 'Send'}
        </button>
      </div>
    </div>
  );
};

export default Chatbot;